### ISSUE TITLE
Unable to `npm run build` monorepo

### ISSUE THREAD

**Issue by tim-lai** [swagger-api/apidom#1725]
### Q&A (please complete the following information)
 - OS: macOS 11.6.7
 - Browser: n/a
 - Version: n/a
 - Method of installation: npm
 - ApiDOM version: v0.35.1
 - Swagger/OpenAPI/AsyncAPI version: n/a

### How can we help?

Steps taken:
`npm i` OK
`npm run prebuild` OK

`npm run build` FAILS

```
lerna ERR! npm run build stderr:
Error: /Repos/apidom/babel.config.cjs: Error while loading config - Cannot find module 'node:path'
Require stack:
- /Repos/apidom/babel.config.cjs
- /Repos/apidom/node_modules/@babel/core/lib/config/files/module-types.js
- /Repos/apidom/node_modules/@babel/core/lib/config/files/configuration.js
- /Repos/apidom/node_modules/@babel/core/lib/config/files/index.js
- /Repos/apidom/node_modules/@babel/core/lib/index.js
- /Repos/apidom/node_modules/@babel/cli/lib/babel/options.js
- /Repos/apidom/node_modules/@babel/cli/lib/babel/index.js
- /Repos/apidom/node_modules/@babel/cli/bin/babel.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/Users/timothy.lai/Repos/apidom/babel.config.cjs:1:14)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Module.require (internal/modules/cjs/loader.js:974:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Repos/apidom/babel.config.cjs',
    '/Repos/apidom/node_modules/@babel/core/lib/config/files/module-types.js',
    '/Repos/apidom/node_modules/@babel/core/lib/config/files/configuration.js',
    '/Repos/apidom/node_modules/@babel/core/lib/config/files/index.js',
    '/Repos/apidom/node_modules/@babel/core/lib/index.js',
    '/Repos/apidom/node_modules/@babel/cli/lib/babel/options.js',
    '/Repos/apidom/node_modules/@babel/cli/lib/babel/index.js',
    '/Repos/apidom/node_modules/@babel/cli/bin/babel.js'
  ]
}
```

**Comment by tim-lai** [comment]
solved. reminder to self to use Node@16

**Comment by char0n** [comment]
yep, it all here: https://github.com/swagger-api/apidom/#development

The same applies for SwaggerEditor@next
